# Generated by Django 5.1.3 on 2024-11-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
