# Generated by Django 5.1.3 on 2024-11-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica5', '0002_alter_membresia_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
