# Generated by Django 5.1.3 on 2024-11-14 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epica4', '0002_catalogo_id_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo de Mensaje',
                'verbose_name_plural': 'Tipos de Mensaje',
                'db_table': 'TipoMensaje',
            },
        ),
        migrations.CreateModel(
            name='TipoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo de Sala',
                'verbose_name_plural': 'Tipos de Sala',
                'db_table': 'TipoSala',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'db_table': 'OrdenCompra',
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epica4.articulo', verbose_name='Articulo')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epica6.ordencompra', verbose_name='Orden de Compra #')),
            ],
            options={
                'verbose_name': 'Detalle de Artículo',
                'verbose_name_plural': 'Detalles de Artículos',
                'db_table': 'Detalle',
            },
        ),
        migrations.CreateModel(
            name='SalaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('usuarios', models.ManyToManyField(related_name='salas', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios en la sala')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epica6.tiposala', verbose_name='Tipo de Sala')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'db_table': 'SalaChat',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=2000, verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epica6.salachat', verbose_name='Sala')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epica6.tipomensaje', verbose_name='Tipo de Mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'Mensaje',
            },
        ),
    ]
