# Generated by Django 5.1.3 on 2024-11-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
