# Generated by Django 5.1.3 on 2024-11-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica1', '0004_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiene_marca',
            field=models.BooleanField(default=False, verbose_name='Tiene marca'),
        ),
    ]
