# Generated by Django 5.1.3 on 2024-11-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica1', '0005_usuario_tiene_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_vendedor',
            field=models.BooleanField(default=False, verbose_name='Es usuario vendedor: '),
        ),
    ]
