# Generated by Django 5.1.3 on 2025-01-06 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica1', '0006_usuario_es_vendedor'),
        ('epica2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epica2.escuelaprofesional', verbose_name='Escuela Profesional'),
        ),
    ]
