# Generated by Django 5.1.3 on 2025-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica1', '0007_alter_usuario_id_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
