# Generated by Django 5.1.3 on 2024-11-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica4', '0003_alter_catalogo_espacio_ocupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=10.0, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
