# Generated by Django 5.1.3 on 2024-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epica4', '0006_alter_catalogo_id_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
    ]
