# Generated by Django 5.1.3 on 2024-11-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epica4', '0005_alter_catalogo_options_alter_catalogo_id_marca'),
        ('epica4', '0007_articulo_bloqueado'),
    ]

    operations = [
    ]
